---
- name: Install PHP packages on Apache
  sudo: yes
  apt: pkg={{item}} state=latest
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - php5-intl
    - php5-curl

- name: enable php5-mcrypt
  sudo: true
  command: php5enmod mcrypt

- name: restart apache
  sudo: yes
  service: name=apache2 enabled=yes state=restarted

- name: Install phpunit
  get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit mode=555
  sudo: true

- name: Install Composer globally
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  sudo: true
